applications:
  locust-tester:
    # The type of the application to build for the load tester.
    type: "python:3.11"
    # The location of the application's code.
    source:
      root: "/"
    hooks:
      build: |
        # Install Python dependencies from requirements.txt
        pip install -r requirements.txt
    web:
      commands:
        start: locust -f locustfile.py --web-port $PORT --web-host=0.0.0.0
    variables:
      env:
        # IMPORTANT: Set this to the public URL of the application you want to test.
        # For example, your main production URL.
        TARGET_HOST: 'https://main-bvxea6i-r7lsq3g4osqao.eu-3.platformsh.site'



routes:
  "https://{default}/":
    type: upstream
    # This must match the 'name' in .upsun/config.yaml
    upstream: "locust-tester:http"
